name: "Check if PR comment says its been approved"
on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world !"
  check-state:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'qa'
    steps:
      - name: Find last comment
        id: find-last-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-author: 'github-actions[bot]'
          body-includes: 'Change has now been approved'
