name: "Check if PR comment says its been approved"
on:
  pull_request_review:
    types: [submitted]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world !"
  check-state:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'qa'
    steps:
      - name: Find last comment
        id: fc
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{github.event.pull_request.number}}
          body-includes: 'approved'
      - run: |
        echo ${{ steps.fc.outputs.comment-id }}
        echo ${{ steps.fc.outputs.comment-body }}
        echo ${{ steps.fc.outputs.comment-author }}
