name: "Deploy Artifact from Artifactory"
on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Application to be deployed.'
        required: true
        
      artifact:
        description: 'artifact version to be deployed'
        required: true
      
      environment:
        description: 'Which environment to be deployed'
        required: true
jobs:
  echo-parameters:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying $APP_NAME v$ARTIFACT to $environment"