name: "Deploy Artifact from Artifactory"

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Application to be deployed.'
        required: true
        
      artifact:
        description: 'artifact version to be deployed'
        required: true
      
      environ:
        type: choice
        description: 'Which environment to be deployed'
        options: 
        - qa
        - preprod
        - demo
        - prod

jobs:
  echo-parameters:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying ${{ github.event.inputs.app-name }} v${{ github.event.inputs.artifact }} to ${{ github.event.inputs.environ }}"